name: Update Data

on:
  schedule:
    - cron: '0 22 * * *' # This sets the action to run every night at 10 PM UTC
  workflow_dispatch: # This allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Replace with your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Ensure you have a requirements.txt file listing necessary packages

    - name: Run update script
      run: python OpenFootprint/products/pull/update_csv_and_yaml.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update CSV and YAML files with new data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
